### ISSUE TITLE
Change package name to `@types` convention for automatic discovery

### ISSUE THREAD

**Issue by mnaoumov** [ophidian-lib/electron-types#1]

**Comment by pjeby** [comment]
Um... why?  There's already a `@types/electron` and it doesn't work, so you have to manually edit your project to use this anyway, and adding a line for `import "@ophidian/electron-types";` somewhere in your codebase is all it takes

For future reference, when filing bug requests or feature reports to open source projects, it's a good idea to begin with a rationale for why you want the change or believe it would be useful.  After all, if the people who created the project knew *why* your request was a good idea, they might have done it already. :wink:   (Also, when people leave issue descriptions blank I sometimes don't see the notification email and don't always realize an issue has been filed to start with.)

**Comment by mnaoumov** [comment]
Sorry, I failed to explain myself better.

`@types/electron` is heavily outdated https://www.npmjs.com/package/@types/electron

So essentially your package is the up-to-date replacement for `@types/electron`

According to TypeScript [convention](https://www.typescriptlang.org/tsconfig#typeRoots), by default all `@types/[name]` packages are being automatically discovered, so you just need to add the npm package for it to work and no need to write any `import` statements.

Regarding my suggestion about double underscore `__`, I followed the [convention](https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-scoped-packages)

**Comment by pjeby** [comment]
My understanding is that the `@types` namespace on npm is managed by the [DefinitelyTyped project](https://github.com/DefinitelyTyped/DefinitelyTyped), and their policy is that:

> When a package [bundles](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) its own types, types should be removed from Definitely Typed to avoid confusion.

Which is why `@types/electron` is outdated.  Electron publishes its own types now.  It's just that they don't provide a way to get the types without installing all of Electron.

Anyway, simply *naming* this package with `@types` isn't going to help anything, because (at least to my understanding) you can't register a package on npm under `@types` without the approval of the DefinitelyTyped project, and doing so in this case would go against their policies.

What you *can* do, however, is put this in your package.json:

```json
"@types/electron": "npm:@ophidian/electron-types@24.3.1",
```

And get the same effect, as far as I can tell.  In other words, you don't need to rename this package to get an auto-import.  (I've now added this info to the README to avoid further confusion.)

**Comment by mnaoumov** [comment]
@pjeby thanks for the clarification. I didn't think of npm publishing policy. My issue and PR don't make sense anymore
